### ISSUE TITLE
[Suggestion] Inherit Particle Texture And Sound Type

### ISSUE THREAD

**Issue by ChloeDawn** [elucent/Blockcraftery#10]
Frames could inherit the particle texture and sound type of their contained blockstate.

**Comment by elucent** [comment]
Particle texture isn't possible. Or rather, of course it's possible, but it's not happening because BakedModels do not have access to blockstate information when getting the particle texture.

While I could add sound type support, this isn't a mod about disguising blocks. Think of it as wallpaper. Since we're stuck with the frame particles anyway, I want to make it clear that the texture is just a thin layer on top of the frame. 

In addition, the sound type support would require an additional TE lookup every time a sound is played. It's unnecessary and will not be added.
